[package]
name = "flatbuffers_structs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "22.10.26"

[build-dependencies]
flatc-rust = "*"
glob = "*"
